name: Build EXE
env:
  APP_NAME: "歌詞改行ツール"
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: ソース取得
        uses: actions/checkout@v4

      - name: バージョン取得
        shell: powershell
        run: |
          echo "VERSION=${env:GITHUB_REF_NAME}" >> $env:GITHUB_ENV


      - name: Pythonセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: PyInstallerインストール
        run: pip install pyinstaller

      - name: EXE作成
        run: |
          pyinstaller --onefile --windowed --name "歌詞改行ツール" --icon icon.ico lyrics_formatter.py

      - name: 配布フォルダ作成
        shell: powershell
        run: |
          $folder = "release\$env:APP_NAME`_$env:VERSION"

          New-Item -ItemType Directory -Force $folder

          Copy-Item "dist\$env:APP_NAME.exe" $folder
          Copy-Item "icon.ico" $folder
          Copy-Item "Read me.txt" $folder

      - name: ZIP作成
        shell: powershell
        run: |
          $folder = "release\$env:APP_NAME`_$env:VERSION"

          Compress-Archive `
            -Path $folder `
            -DestinationPath "release\$env:APP_NAME`_$env:VERSION.zip"

      - name: テスト版をArtifactsに保存
        uses: actions/upload-artifact@v4
        with:
          name: 歌詞改行ツール_${{ env.VERSION }}
          path: release/*.zip

      - name: Release作成
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.zip
          name: 歌詞改行ツール ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true